# -*- coding: utf-8 -*-
"""AS2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xKOqaexTvymEQEC1blOLb5h3FNa4_gjf
"""

# Logistic Regression using Single Layer Perceptron (SLP)
# Glass Classification

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Load dataset (upload glass.csv from Kaggle)
data = pd.read_csv('/content/glass.csv')

# Drop ID column if present
if 'Id' in data.columns or 'Id_number' in data.columns:
    data = data.drop(columns=['Id'], errors='ignore')
    data = data.drop(columns=['Id_number'], errors='ignore')

# Features and target
X = data.drop('Type', axis=1)
y = data['Type']

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Feature scaling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Logistic Regression (Single Layer Perceptron style classifier)
model = LogisticRegression(max_iter=1000)

# Train model
model.fit(X_train, y_train)

# Predictions
y_pred = model.predict(X_test)

# Accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Evaluation
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))