# -*- coding: utf-8 -*-
"""AS1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xKOqaexTvymEQEC1blOLb5h3FNa4_gjf
"""

import numpy as np

# Step activation function
def step_function(x):
    if x >= 0:
        return 1
    else:
        return 0

# Perceptron function
def perceptron(x1, x2, w1, w2, b):
    weighted_sum = w1*x1 + w2*x2 + b
    return step_function(weighted_sum)

# Inputs
inputs = [(0,0), (0,1), (1,0), (1,1)]

# -------- AND Gate --------
print("AND Gate")
for x1,x2 in inputs:
    y = perceptron(x1,x2,1,1,-1.5)
    print(x1,x2,"->",y)

print()

# -------- OR Gate --------
print("OR Gate")
for x1,x2 in inputs:
    y = perceptron(x1,x2,1,1,-0.5)
    print(x1,x2,"->",y)

print()

# -------- NAND Gate --------
print("NAND Gate")
for x1,x2 in inputs:
    y = perceptron(x1,x2,-1,-1,1.5)
    print(x1,x2,"->",y)

print()

# -------- NOR Gate --------
print("NOR Gate")
for x1,x2 in inputs:
    y = perceptron(x1,x2,-1,-1,0.5)
    print(x1,x2,"->",y)