# -*- coding: utf-8 -*-
"""AS4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xKOqaexTvymEQEC1blOLb5h3FNa4_gjf
"""

# Multilayer Perceptron using Backpropagation
# Abalone Age Prediction

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPRegressor
from sklearn.metrics import mean_squared_error

# Column names from dataset description
columns = ['Sex','Length','Diameter','Height','Whole_weight',
           'Shucked_weight','Viscera_weight','Shell_weight','Rings']

# Load dataset
data = pd.read_csv('/content/abalone.data', names=columns)

print(data.head())

# Convert categorical column
data = pd.get_dummies(data, columns=['Sex'])

# Features and target
X = data.drop('Rings', axis=1)
y = data['Rings']

# Train test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Feature scaling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Multilayer Perceptron model
mlp = MLPRegressor(
    hidden_layer_sizes=(10,10),
    activation='relu',
    solver='adam',
    max_iter=500
)

# Train model
mlp.fit(X_train, y_train)

# Predictions
y_pred = mlp.predict(X_test)

# Evaluation
mse = mean_squared_error(y_test, y_pred)

print("\nMean Squared Error:", mse)