# -*- coding: utf-8 -*-
"""AS3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xKOqaexTvymEQEC1blOLb5h3FNa4_gjf
"""

# Multiple Linear Regression using Perceptron (Gradient Descent)

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error

# Load dataset
data = pd.read_csv('/content/multiple_linear_regression_dataset.csv')

print("Dataset:")
print(data.head())

# Separate features and target
X = data[['Age','Experience','Education_Level']]
y = data['Salary']

# Train test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Feature scaling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Convert to numpy arrays
X_train = np.array(X_train)
X_test = np.array(X_test)
y_train = np.array(y_train)

# Initialize weights and bias
weights = np.zeros(X_train.shape[1])
bias = 0

learning_rate = 0.01
epochs = 1000

# Training loop
for epoch in range(epochs):

    y_pred = np.dot(X_train, weights) + bias
    error = y_pred - y_train

    # gradients
    dw = np.dot(X_train.T, error) / len(y_train)
    db = np.sum(error) / len(y_train)

    # update weights
    weights -= learning_rate * dw
    bias -= learning_rate * db

# Testing
y_test_pred = np.dot(X_test, weights) + bias

# Evaluation
mse = mean_squared_error(y_test, y_test_pred)

print("\nWeights:", weights)
print("Bias:", bias)
print("Mean Squared Error:", mse)